version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/app
    networks:
      - usage-dashboard

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev  # Use the dev stage for development
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - usage-dashboard

  # test:
  #   build:
  #     context: ./backend  # Adjust this path to where your Dockerfile is located
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/app  # Mount your backend code into the container
  #   command: pytest
  #   environment:
  #     - PYTHONPATH=/app
  #   depends_on:
  #     - backend

networks:
  usage-dashboard:
    driver: bridge
